travis:
  secure:
    BINSTAR_TOKEN: snRlofrKoBc8Xyai1YIHcKC1bliM1TWTy/grP3VQjwlcmErZxr+7L2GDswCAZsSlzJA0ygKaHaFOQu8+RdN2wo5c/3LKdNWCPLu2PluMER5GIVupwPVraGcnk6Jwkutcv7oDM8mZZZe2IDRQBgipmCCwHqhCFTzE4agnFwN8Rzgsx93DE3WXm1h16i+lYxIB8Z3RhH4BhVwnMAWRtqellOggCZINH2+/WrwIaRKSynUVQSnCJCIqs6/kppkfrgj3voMIbRYRhigJCf6Sl9ttWkjqmO+j5kObVukY6S6QnXTh6EVer+H2HYhx6bPs3Il5VBn+lopfmbRB+u4cP6Tjm7+j/YWsR7i8I/V7U98rz6R9FsNNeGM0UzbQGXa48KaQWSUVxCROnwGXu4BKO1QlqO/4Cf3y9Fw3MQL3DmRdLo9Lu5bbZYwA0W51ab6ZL/xhRoklFoi+kIjJ8qErXYZz7H/a78jWCkfmCsBeyllaa2QFrGOA3oVgmi6t5yD2zJYqqtvcwguSN8pi38OAgurzMwKmQXv/MrSNqpAXWDzK+K036dkC0g12eCIgrp4IaiuE7GMne7tsaDiXwmfOxcMvpqzVVDJwjxC51Rg3EVhwZcoa7m7w2HAuAIP5EuERi+u7fWbg/oe4r/NnEgn05M1OThlCzp5sayhXjli6H8i7IlI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
